name: FirstPlugin
version: 1.0-SNAPSHOT
author: Bones Gerling
main: us.bones.firstplugin;
api-version: 1.15.2

depend: //tell the server that an external plugin must be loaded before your plugin can be loaded
website: //your website appear with /version <pluginname>
commands: // if you have some commands
  <command>:
    description: //describe your command it will appear with /help
    usage: //how is the commands' syntax