name: FirstPlugin
version: 1.0-SNAPSHOT
author: Bones Gerling
main: us.bones.firstplugin;
api-version: 1.15.2

commands:
  pos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"